//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Vipolnenie_zayavki = new HashSet<Vipolnenie_zayavki>();
        }
    
        public int ID_sotrudnika { get; set; }
        public Nullable<int> ID_usera { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<System.DateTime> Data_rojdeniya { get; set; }
        public int Doljnost { get; set; }
        public string Adres { get; set; }
        public string Nomer_telefona { get; set; }
    
        public virtual Doljnost Doljnost1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vipolnenie_zayavki> Vipolnenie_zayavki { get; set; }
    }
}
