//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vipolnenie_zayavki
    {
        public int ID_vipolneniya_zayavki { get; set; }
        public System.DateTime Data_nachala { get; set; }
        public System.DateTime Data_okonchaniya { get; set; }
        public int ID_sotrudnika { get; set; }
        public decimal Stoimost { get; set; }
        public Nullable<int> ID_zayavki { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Zayavka Zayavka { get; set; }
    }
}
